import Head from 'next/head'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Form from '../components/02-molecules/form';

export default function Home() {
  return (
    <>
      <Head>
        <title>Using MUI with Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack spacing={4}>
          <Form />
        </Stack>
      </main>
    </>
  )
}
